# baseURL = "https://raditian-hugo.radity.com/"
languageCode = "en-us"
theme = "raditian-free-hugo-theme"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  # Header
  [[menu.header]]
  name = "Tentang kami"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Layanan Kami"
  URL = "#ourservice"
  weight = 3

  [[menu.header]]
  name = "Artikel"
  URL = "#product"
  weight = 4

  [[menu.header]]
  name = "Klien"
  URL = "#client"
  weight = 5
  
  # [[menu.header]]
  # name = "Our Team"
  # URL = "#ourteam"
  # weight = 5

  [[menu.header]]
  name = "Kontak kami"
  URL = "#contact"
  weight = 6

  #Footer
  [[menu.footer]]
  name = "Tentang kami"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "Layanan Kami"
  URL = "#ourservice"
  weight = 3

  [[menu.footer]]
  name = "Artikel"
  URL = "#product"
  weight = 4
  
  [[menu.footer]]
  name = "Klien"
  URL = "#client"
  weight = 5
  
  # [[menu.footer]]
  # name = "Our Team"
  # URL = "#ourteam"
  # weight = 5

  [[menu.footer]]
  name = "Kontak kami"
  URL = "#contact"
  weight = 6


[params]

  sections = [
    "showcase", 
    "about", 
    "what-we-do", 
    "why", 
    "our-service", 
    "product", 
    "client", 
    "contact", 
    "newsletter"
  ]

  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "Astramaya"

  [params.footer]
      copyright = "Â© Astramaya. All rights reserved."
      [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"